# Do not edit this file.

source 'https://rubygems.org'

gem 'pry'
gem 'sinatra'
gem 'sinatra-contrib'

gem 'activesupport'

gem "sinatra-activerecord", :git => "https://github.com/janko-m/sinatra-activerecord.git"
gem "pg"

gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'

gem "minitest-rg"

gem "dotenv"

gem "rake"
gem "database_cleaner"
gem 'simplecov', :require => false, :group => :test

gem 'carrierwave'
gem 'mini_magick'

gem "fog"
gem "fog-aws"

gem 'rubocop', '~> 0.37.2', require: false
gem 'inch', require: false