# This module handles user validation methods that aren't model specific.
module Errors

  #tells user whether input to form is valid
  #
  #returns Boolean true or false
  def is_valid?
    self.set_errors
    
    if @errors.length > 0
      return false
    else
      return true
    end
  end

  #returns Array generated by set_errors method
  #
  #returns @errors Array of Strings
  def get_errors
    self.set_errors
    return @errors
  end

end